server:
  port: 9000
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
#    url: jdbc:mysql://localhost:3306/db_example
#    username: root
#    password: 1234567890
    url: jdbc:mysql://aurora-poc-1.cluster-c4oq3mi118xy.ap-south-1.rds.amazonaws.com:3306/db_example
    username: admin
    password: paytm#123
    driver-class: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: 10.211.46.61:9092
    producer:
      transaction-id-prefix: tx-
    #      properties:
    #        enable.idempotence: true
    consumer:
      bootstrap-servers: 10.211.46.61:9092
      group-id: test-group
      enable-auto-commit: false
      isolation-level: read_committed
    topics: example.db_example.order

